import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import EccoLayout from "@/components/EccoLayout/EccoLayout";
import "@/styles/textFont.css";
import "@/styles/positions.css";
import "@/styles/iconStyles.css";
import "@/styles/widthMarginPadding.css";
import "@/styles/sizes.css";
import "@/styles/colors.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Eccosphere The Coworking Sanctuary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <EccoLayout>{children}</EccoLayout>
        <Script id="zoho-salesiq-init" strategy="afterInteractive">
          {`
    window.$zoho = window.$zoho || {};
    $zoho.salesiq = $zoho.salesiq || {
      ready: function () {
        // You can place additional configuration here
        console.log("Zoho SalesIQ is ready");
      }
    };
  `}
        </Script>
        <Script
          id="zsiqscript"
          src="https://salesiq.zohopublic.in/widget?wc=siq5a9a153358da43f0350a9dc8ea590dcb546e4cddeacc699456496e2e1e94d63d"
          defer
        ></Script>
      </body>
    </html>
  );
}
