import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import EccoLayout from "@/components/EccoLayout/EccoLayout";
import "@/styles/textFont.css";
import "@/styles/positions.css";
import "@/styles/iconStyles.css";
import "@/styles/widthMarginPadding.css";
import "bootstrap/dist/css/bootstrap.min.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Eccosphere The Coworking Sanctuary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <EccoLayout>{children}</EccoLayout>
      </body>
    </html>
  );
}
